#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

const YII_DEBUG = false;
const YII_ENV = 'production';

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

$autoloadLocations = [
  __DIR__ . '/../vendor/autoload.php',
  '/data/vendor/autoload.php',
];

foreach ($autoloadLocations as $location) {
  if (file_exists($location)) {
    require_once $location;
    break;
  }
}

use Sil\PhpEnv\Env;
use SimpleSAML\Module\silauth\Auth\Source\config\ConfigManager;

$dbAttributes = [];
$caFile = "/data/vendor/simplesamlphp/simplesamlphp/cert/rds_ca.pem";
if (file_exists($caFile)) {
  $dbAttributes = [
    PDO::MYSQL_ATTR_SSL_CA => $caFile,
    PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => 1,
  ];
}

$application = ConfigManager::getYii2ConsoleApp(['components' => ['db' => [
  'dsn' => sprintf(
    'mysql:host=%s;dbname=%s',
    Env::get('MYSQL_HOST'),
    Env::get('MYSQL_DATABASE')
  ),
  'username' => Env::get('MYSQL_USER'),
  'password' => Env::get('MYSQL_PASSWORD'),
  'attributes' => $dbAttributes,
]]]);
$exitCode = $application->run();
exit($exitCode);
